# Generated by Django 4.0 on 2022-01-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(default=1, max_length=600, verbose_name='link'),
            preserve_default=False,
        ),
    ]
