# Generated by Django 4.0 on 2022-01-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_card_src_card_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='imagen',
        ),
        migrations.AddField(
            model_name='card',
            name='src',
            field=models.CharField(default=1, max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
